controller_list:
 - name: arm_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   allowed_execution_duration_scaling: 1.2
   allowed_goal_duration_margin: 0.5
   default: true
   joints:
     - base2base_joint
     - base_joint
     - elbow_joint
     - wrist_joint
     - hand_joint
 - name: hand_controller
   action_ns: gripper_action
   type: GripperCommand
   default: true
   parallel: true
   joints:
     - finger_joint1
     - finger_joint2
