controller_list:
 - name: arm_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   joints: [base2base_joint, base_joint, elbow_joint, wrist_joint, hand_joint, end_joint]

