controller_list:
  - name: fake_gripper_controller
    joints:
      - finger_joint1
      - finger_joint2
  - name: fake_arm_controller
    joints:
      - base2base_joint
      - base_joint
      - elbow_joint
      - wrist_joint
      - hand_joint