controller_list:
  - name: fake_arm_controller
    joints:
      - base2base_joint
      - base_joint
      - elbow_joint
      - wrist_joint
  - name: fake_hand_controller
    joints:
      - hand_joint
      - finger_joint1
      - finger_joint2